---
swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: Hola que tal

  version: production
basePath: https://afine.com
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/alba":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - somettext
      operationId: findAccounts
      summary: this is example text
 
